import React from 'react';
import { usePlatform } from '../context/PlatformContext';
import { 
  CheckCircle, 
  Lightbulb, 
  Droplet, 
  Sprout, 
  Map, 
  ShieldAlert, 
  TrendingUp 
} from 'lucide-react';

export default function RecommendationsView() {
  const { recommendations } = usePlatform();

  if (recommendations.length === 0) {
    return (
      <div className="glass-card" style={{ padding: '3rem', textAlign: 'center' }}>
        <Lightbulb size={48} style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }} />
        <h3>No Recommendations Available</h3>
        <p style={{ color: 'var(--text-secondary)' }}>Add dataset records to generate agricultural insights.</p>
      </div>
    );
  }

  const getIcon = (type) => {
    switch (type) {
      case 'crop': return <Sprout size={20} style={{ color: 'var(--primary)' }} />;
      case 'water': return <Droplet size={20} style={{ color: 'var(--secondary)' }} />;
      case 'soil': return <Map size={20} style={{ color: 'var(--warning)' }} />;
      case 'input': return <ShieldAlert size={20} style={{ color: 'var(--danger)' }} />;
      default: return <Lightbulb size={20} style={{ color: 'var(--primary)' }} />;
    }
  };

  return (
    <div className="content-body">
      <div className="glass-card">
        <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
          <Lightbulb size={24} style={{ color: 'var(--warning)' }} /> AI Decision Recommendations
        </h2>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '1.5rem' }}>
          Real-time agronomic insights generated by running comparative statistical efficiency engines on the active dataset.
        </p>

        <div className="rec-cards-grid">
          {recommendations.map(rec => (
            <div key={rec.id} className={`glass-card rec-card urgency-${rec.urgency}`}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.75rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  {getIcon(rec.type)}
                  <h4 style={{ fontWeight: '700' }}>{rec.title}</h4>
                </div>
                <span className={`rec-badge rec-badge-${rec.urgency}`}>
                  {rec.urgency} Priority
                </span>
              </div>

              <div style={{ fontSize: '1rem', fontWeight: '700', color: 'var(--text-primary)', marginBottom: '0.5rem' }}>
                {rec.metric}
              </div>

              {/* Render description handling markdown bold manually */}
              <p 
                style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.5' }}
                dangerouslySetInnerHTML={{
                  __html: rec.description.replace(/\*\*(.*?)\*\*/g, '<strong style="color: var(--text-primary)">$1</strong>')
                }}
              ></p>

              <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', marginTop: '1rem', fontSize: '0.75rem', color: 'var(--primary)' }}>
                <CheckCircle size={12} />
                <span>Computed dynamically from active csv records</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* AI Insight Cards */}
      <div className="glass-card" style={{ background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.05) 0%, rgba(6, 182, 212, 0.05) 100%)' }}>
        <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <TrendingUp size={18} style={{ color: 'var(--primary)' }} /> Agronomic Sustainability Outlook
        </h3>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
          Our models indicate that shifting flood-irrigated farms to drip-irrigation holds the highest potential for overall sustainability score improvement. 
          Farms that implement sprinkler irrigation show moderate crop yield improvements, but require active water regulation to prevent excessive consumption. 
          Additionally, loamy soils consistently show higher fertilizer-to-yield conversion rates compared to sand-dominant fields.
        </p>
      </div>
    </div>
  );
}
